import numpy as np 
a=np.array([1,2,3,4,5,6,7])
print("the array is:",a)
sum=np.sum(a)
print("the sum is:",sum)
avg=np.mean(a)
print("the average is:",avg)
min=np.min(a)
print("the inimum value is:",min)
max=np.max(a)
print("the maximum value is:",max)
min_index=np.argmin(a)
print("the minimum index is:",min_index)
max_index=np.argmax(a)
print("the maximum index is:",max_index)
std=np.std(a)
print("the standard devitaion is:",std)
var=np.var(a)
print("the variance is:",var)

